name: "Push to the server."
author: "Techflash"
description: "Pushes the changes from the push to the web server."
on:
	push:
		branches: [ master ]
	pull_request:
		branches: [ master ]
jobs:
	build:
		runs-on: ubuntu-latest
    	name: Build and Test
    		steps:
    			- uses: actions/checkout@v2
		name: Check out repository
			- uses: actions/setup-node@v1
      	name: Set up Node.js
      		with:
        	node-version: 17
    		- run: |
        	node .
